import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    topNav: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: 60,
        paddingHorizontal: 20,
        paddingBottom: 10,
    },
    navAction: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
    },
    navActionText: {
        marginLeft: 6,
        fontSize: 14,
        fontWeight: '600',
    },
    navProfile: {
        padding: 2,
    },
    avatarMini: {
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
    },
    avatarInitial: {
        color: '#FFF',
        fontSize: 14,
        fontWeight: '700',
    },
    scrollContent: {
        paddingBottom: 100,
    },
    headerTitleArea: {
        paddingHorizontal: 20,
        paddingTop: 10,
        marginBottom: 25,
    },
    userName: {
        fontSize: 34,
        fontWeight: '700',
        letterSpacing: -0.5,
    },
    headerSubtitle: {
        fontSize: 17,
        marginTop: 2,
        fontWeight: '400',
        opacity: 1,
    },
    sectionGroup: {
        paddingHorizontal: 20,
    },
    metaHeader: {
        marginBottom: 16,
    },
    metaTitle: {
        fontSize: 20,
        fontWeight: '600',
    },
    metaDate: {
        fontSize: 13,
        marginTop: 2,
        fontWeight: '400',
    },
    iosCardMain: {
        borderRadius: 24,
        padding: 24,
        marginBottom: 0,
        backgroundColor: 'transparent',
    },
    gaugeHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    cardTag: {
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    gaugeContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 10,
        marginBottom: 20,
    },
    gaugeContent: {
        position: 'absolute',
        top: '40%',
        alignItems: 'center',
    },
    gaugeUnits: {
        fontSize: 44,
        fontWeight: '800',
        letterSpacing: -1,
    },
    gaugeSublabel: {
        fontSize: 12,
        fontWeight: '500',
        marginTop: -2,
        opacity: 0.6,
        textTransform: 'uppercase',
    },
    rumoContainer: {
        marginTop: 8,
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
    },
    rumoAo: {
        fontSize: 11,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    gaugeMetaName: {
        fontSize: 11,
        fontWeight: '700',
        marginTop: 4,
        textAlign: 'center',
    },
    gaugeMetaDate: {
        fontSize: 10,
        fontWeight: '400',
        marginTop: 0,
        opacity: 0.8,
    },
    pillsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginTop: 20,
        gap: 10,
    },
    levelPill: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        padding: 8,
        borderRadius: 20,
        borderWidth: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 2,
    },
    pillIconBg: {
        width: 28,
        height: 28,
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 6,
    },
    pillIcon: {
        width: 16,
        height: 16,
        resizeMode: 'contain',
    },
    pillPercent: {
        fontSize: 14,
        fontWeight: '700',
    },
    pillLabel: {
        fontSize: 12,
        fontWeight: '400',
    },
    levelBadge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
    },
    levelBadgeText: {
        fontSize: 11,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    iosCard: {
        borderRadius: 24,
        padding: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.08,
        shadowRadius: 15,
        elevation: 6,
    },
    verticalLine: {
        position: 'absolute',
        width: 2,
        opacity: 0.5,
        zIndex: 1,
        top: 40,
        height: 130,
    },
    chartTooltip: {
        position: 'absolute',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 10,
        minWidth: 80,
    },
    tooltipMonth: {
        fontSize: 10,
        fontWeight: '700',
        color: '#AEAEB2',
        marginBottom: 2,
        textTransform: 'uppercase',
    },
    tooltipValue: {
        fontSize: 14,
        fontWeight: '800',
        color: '#FFFFFF',
    },
    forecastSection: {
        marginTop: 10,
    },
    sectionTitle: {
        fontSize: 13,
        fontWeight: '600',
        marginBottom: 12,
        marginLeft: 4,
        letterSpacing: 0.5,
    },
    forecastCard: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        borderRadius: 16,
    },
    forecastIconBg: {
        width: 36,
        height: 36,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    forecastInfo: {
        flex: 1,
    },
    forecastSubtext: {
        fontSize: 12,
        marginBottom: 2,
    },
    forecastMainValue: {
        fontSize: 20,
        fontWeight: '700',
    },
    iosAlertCard: {
        flexDirection: 'row',
        padding: 16,
        borderRadius: 20,
        marginTop: 16,
        borderWidth: 1,
        alignItems: 'center',
    },
    alertIconBg: {
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    alertContent: {
        flex: 1,
    },
    alertTitle: {
        fontSize: 14,
        fontWeight: '700',
        marginBottom: 2,
    },
    alertDescription: {
        fontSize: 13,
        lineHeight: 18,
    },
    emptyContainer: {
        padding: 60,
        alignItems: 'center',
    },
    emptyText: {
        fontSize: 17,
        marginTop: 12,
        marginBottom: 16,
    },
    historyLinkText: {
        fontSize: 16,
        fontWeight: '600',
    },
    iosFab: {
        position: 'absolute',
        bottom: 34,
        right: 20,
        width: 60,
        height: 60,
        borderRadius: 30,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 9999,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 15,
        elevation: 15,
    },
    iosModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.3)',
        justifyContent: 'flex-end',
    },
    iosMenuSheet: {
        width: '100%',
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        padding: 24,
    },
    menuHeader: {
        alignItems: 'center',
        marginBottom: 24,
    },
    menuAvatarLarge: {
        width: 72,
        height: 72,
        borderRadius: 36,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 5,
    },
    avatarLabelLarge: {
        fontSize: 28,
        fontWeight: '700',
    },
    menuName: {
        fontSize: 22,
        fontWeight: '700',
    },
    menuRole: {
        fontSize: 14,
        marginTop: 2,
    },
    menuSeparator: {
        height: StyleSheet.hairlineWidth,
        marginHorizontal: -24,
    },
    menuActionItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 18,
    },
    logoutText: {
        fontSize: 17,
        fontWeight: '600',
    },
    footer: {
        paddingVertical: 40,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
    },
    footerText: {
        fontSize: 12,
        fontWeight: '500',
        letterSpacing: 1,
        textTransform: 'capitalize',
    },
    fixedBottomNav: {
        position: 'absolute',
        bottom: 0,
        width: '100%',
        zIndex: 1000,
    },
    navInner: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        height: 60,
        borderTopWidth: 0.5,
    },
    navButtonItem: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    navButtonLabel: {
        fontSize: 10,
        marginTop: 4,
        fontWeight: '600',
    },
});